name: CI

on:
  pull_request:
    branches:
      - develop
      
jobs:
  danger:
    runs-on: ubuntu-latest
    environment: danger
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
    - uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: danger/danger
      run: 
        export DANGER_GITHUB_API_TOKEN = ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        bundle exec danger --verbose 