name: CI

on:
  pull_request:
    branches:
      - develop
      
jobs:
  danger:
    runs-on: ubuntu-latest
    environment: danger
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
    - name: Install Gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Run Danger
      run: |
        export DANGER_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
        bundle exec danger --verbose