name: CI

on:
  pull_request:
    branches:
      - develop
      
jobs:
  danger:
    runs-on: ubuntu-latest
    environment: danger
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
    - name: Run Danger
      run: |
        bundle
        export DANGER_GITHUB_API_TOKEN=${{ secrets.DANGER_GITHUB_API_TOKEN }}
        bundle exec danger --verbose
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}